# Generated by Django 6.0.8 on 2026-09-20 16:08

import core.validators
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0033_outlet_po_vendor_email_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Restaurant Logo for bills', null=True, upload_to=tenants.models.tenant_logo_path, validators=[core.validators.validate_image_size]),
        ),
    ]
