# Generated by Django 6.0.8 on 2026-09-21 13:13

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0034_alter_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='trn_no',
            field=models.CharField(blank=True, help_text='Federal Tax Authority Tax Registration Number (15 digits) — UAE tenants only', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='TRN (Tax Registration Number) must be exactly 15 digits.', regex='^\\d{15}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('AE', 'United Arab Emirates')], default='IN', help_text='Controls the tax regime (GST vs VAT), currency, and every receipt/report/setup-screen label this tenant sees — see tenants.tax_regimes.TAX_REGIMES. Changing this after a tenant has live orders does not retroactively rewrite past bills; it only affects orders created from that point on.', max_length=2),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='gst_no',
            field=models.CharField(blank=True, help_text='Restaurant GSTIN (15 characters, e.g. 29ABCDE1234F1Z5) — India tenants only', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GSTIN (e.g. 29ABCDE1234F1Z5).', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')]),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['country'], name='tenants_ten_country_b9800b_idx'),
        ),
    ]
