# Generated by Django 6.0.8 on 2026-09-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_scheduledreportsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatorconfig',
            name='inhouse_delivery_enabled',
            field=models.BooleanField(default=True, help_text='Enable in-house direct deliveries'),
        ),
    ]
