# Generated by Django 6.0.8 on 2026-09-20 16:08

import core.validators
import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_menuitem_parcel_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=menu.models.menu_item_image_path, validators=[core.validators.validate_image_size]),
        ),
    ]
