# Generated by Django 6.0.8 on 2026-09-17 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0060_delete_payments_models_state_only'),
        ('tenants', '0033_outlet_po_vendor_email_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='table',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('square', 'Square'), ('round', 'Round'), ('rect', 'Rectangle'), ('wall', 'Wall')], default='square', max_length=20),
        ),
        migrations.AddField(
            model_name='table',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FloorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('width', models.IntegerField(default=900)),
                ('height', models.IntegerField(default=500)),
                ('grid_size', models.IntegerField(default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'outlet'], name='orders_floo_tenant__0f3c45_idx')],
                'unique_together': {('tenant', 'outlet', 'name')},
            },
        ),
    ]
