# Generated by Django 6.0.8 on 2026-09-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0061_table_floor_editor_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery'), ('counter', 'Counter / QSR'), ('zomato', 'Zomato'), ('swiggy', 'Swiggy'), ('uber_eats', 'Uber Eats'), ('web', 'Website')], default='dine_in', max_length=20),
        ),
    ]
