# Generated by Django 6.0.8 on 2026-09-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0062_alter_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_ready_at',
            field=models.DateTimeField(blank=True, help_text='Target completion time calculated from prep_time_minutes', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prep_time_minutes',
            field=models.PositiveIntegerField(blank=True, default=15, help_text='Estimated preparation time in minutes set at order confirmation', null=True),
        ),
    ]
